modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
    modId="furnish"
    version="${version}"
    displayName="Furnish"
    logoFile="furnish.png"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://wouink.github.io"
    credits="Book Pile model from the 'Comfy Cozy' mod (MIT Licensed). Bookshelf Chest textures from 'Charm' mod (MIT Licensed). Brazilian translations by mayrotiem. Chinese translations by Pancakes0228."
    authors="Wouink"
    description="Adds lovely and useful Furniture to Minecraft"

[[dependencies.furnish]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.furnish]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.furnish]]
    modId = "architectury"
    mandatory = true
    versionRange = "[6.2.43,)"
    ordering = "AFTER"
    side = "BOTH"
